consolidate_subtopics:
  response_mime_type: application/json

  system_instruction: >
    Você receberá **um único objeto em JSON** com a seguinte estrutura:

    ```json
    {
      "topics": [
        {
          "topic": "Nome do tópico",
          "sub_topics": [
            "Sub-tópico 1 que pode ter conteúdo similar a outros",
            "Sub-tópico 2 que pode ter conteúdo similar a outros"
          ]
        }
      ]
    }
    ```

    Seu objetivo é **consolidar sub-tópicos similares** dentro de cada tópico, mesclando seu conteúdo de forma inteligente para:
    1. Reduzir redundâncias
    2. Preservar todas as informações únicas
    3. Manter a clareza e coesão do texto

    ### Diretrizes para consolidação:
    1. **Identificação de Similaridades**
       - Identifique sub-tópicos que abordam o mesmo conceito ou tema
       - Considere variações de linguagem e diferentes perspectivas do mesmo assunto
       - Analise o contexto completo para evitar falsas similaridades

    2. **Processo de Consolidação**
       - Combine sub-tópicos similares em um único texto coeso
       - Mantenha todas as informações únicas de cada sub-tópico original
       - Elimine apenas redundâncias diretas
       - Organize o conteúdo de forma lógica e fluida

    3. **Resultado Final**
       - Retorne **apenas o JSON** resultante, mantendo a estrutura original:
         ```json
         {
           "topics": [
             {
               "topic": "Nome do tópico",
               "sub_topics": [
                 "Sub-tópico consolidado com todo o conteúdo único preservado"
               ]
             }
           ]
         }
         ```
       - Não inclua texto adicional além do objeto JSON
       - Garanta que o JSON seja válido

    ```json
    {
      "type": "object",
      "properties": {
        "topics": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "topic": {
                "type": "string"
              },
              "sub_topics": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "topic",
              "sub_topics"
            ]
          }
        }
      },
      "required": [
        "topics"
      ]
    }
    ```

    Em resumo: você deve **consolidar sub-tópicos similares** dentro de cada tópico, mesclando seu conteúdo de forma inteligente para reduzir redundâncias enquanto preserva todas as informações únicas, retornando apenas o JSON final.

  user_message: >
    Consolide os sub-tópicos similares do JSON fornecido, preservando todas as informações únicas:

    {content}

    Lembre-se de:
    1. Manter a estrutura do JSON
    2. Preservar todo o conteúdo único
    3. Eliminar apenas redundâncias diretas 