create_topics:
  response_mime_type: application/json

  system_instruction: >
    Crie uma lista estruturada de tópicos e subtópicos de estudo para **cada capítulo e subcapítulo** dos textos anexados, **exceto** introduções e conclusões, retornando **somente** um JSON **válido** com o seguinte formato:

    ```json
    {
      "topics": [
        {
          "topic": "Nome ou número do capítulo/subcapítulo (ex.: Título do Capítulo)",
          "sub_topics": [
            "Conceito-chave aprofundado e específico em formato de texto corrido",
            "Conceito-chave aprofundado e específico em formato de texto corrido",
            "... repita para todos os conceitos relevantes do subcapítulo ..."
          ]
        }
      ]
    }
    ```

    ### Diretrizes detalhadas:

    1. **Estrutura de tópicos**  
      - Cada capítulo ou subcapítulo deve ser representado em um **único** objeto dentro de `"topics"`.  
      - Use a propriedade `"topic"` para nomear o capítulo/subcapítulo no estilo **Título do Capítulo**, **1.1 Título do Subcapítulo** ou **Título da Sub Sub Section**, etc.  
      - Use a propriedade `"sub_topics"` (array de *strings*) para incluir todos os conceitos-chave aprofundados daquele capítulo ou subcapítulo, cada um como um item **separado**. 
      - **Não** inclua números no nome dos tópicos.

    2. **Conteúdo avançado e específico**  
      - Cada elemento de `"sub_topics"` deve ser **detalhado** e **abrangente**, incluindo:
        * Definição técnica completa do conceito com terminologia específica da área
        * Principais características, componentes e propriedades fundamentais
        * Relações e interdependências com outros conceitos relevantes
        * Implicações práticas ou teóricas importantes
        * Limitações, restrições e casos especiais
        * Fundamentação matemática quando aplicável
        * Aspectos metodológicos críticos
        * Estado da arte e desenvolvimentos recentes
      - Extraia do texto base:
        * Todos os termos técnicos relevantes
        * Definições formais e informais
        * Exemplos significativos que ilustrem conceitos complexos
        * Relações causais e correlações importantes
        * Metodologias e frameworks mencionados
        * Debates teóricos e diferentes perspectivas apresentadas
      - Organize os subtópicos de forma que:
        * Conceitos fundamentais precedam conceitos avançados
        * Haja uma linha clara de desenvolvimento do conhecimento
        * As relações entre diferentes áreas sejam explícitas
        * Os pré-requisitos conceituais estejam claramente estabelecidos
      - Evite:
        * Simplificações excessivas de conceitos complexos
        * Omissão de detalhes técnicos importantes
        * Redundância entre subtópicos
        * Generalidades sem conteúdo técnico específico

    3. **Formato e nível de detalhamento**  
      - Mantenha o **nível avançado** e **aprofundado**, visando um leitor especialista em **Ciência de Dados**, **Estatística** e **IA**.  
      - Não use “contexto” como título ou subtítulo.  
      - Não pule nenhuma seção (exceto introduções/conclusões).  

    4. **Exemplo de como preencher `"topics"`**  
      ```json
      {
        "topics": [
          {
            "topic": "Fundamentos Estatísticos",
            "sub_topics": [
              "Teoria da probabilidade e variáveis aleatórias: fundamentação matemática das distribuições de probabilidade, axiomas de Kolmogorov, conceitos de medida e espaço amostral aplicados à modelagem estatística",
              "Inferência estatística e estimação: métodos de máxima verossimilhança, estimadores não-viesados de variância mínima (UMVUE), propriedades assintóticas e eficiência de estimadores",
              "Testes de hipóteses avançados: abordagens frequentista e bayesiana, poder do teste, tamanho do efeito e métodos de correção para múltiplos testes",
              "Teoria da decisão estatística: funções de perda, estimadores de Bayes, minimaxidade e admissibilidade de procedimentos estatísticos"
            ]
          },
          {
            "topic": "Modelos de Aprendizado Profundo",
            "sub_topics": [
              "Arquiteturas de redes neurais: análise comparativa entre CNNs, RNNs e Transformers, incluindo vantagens computacionais e limitações teóricas de cada abordagem",
              "Otimização em deep learning: algoritmos de primeira e segunda ordem, métodos adaptativos, regularização implícita e explícita",
              "Representações aprendidas: teoria da informação aplicada a embeddings, propriedades geométricas do espaço latente, disentanglement de fatores",
              "Generalização em deep learning: complexidade de Rademacher, bounds PAC-Bayes, double descent e reconciliação com teoria estatística clássica"
            ]
          }
        ]
      }
      ```

    5. **Saída Final**  
      - **Retorne apenas o JSON** (sem quaisquer textos adicionais, introduções ou rótulos fora da estrutura em JSON).  
      - Assegure-se de que o JSON seja **válido** e respeite o seguinte schema:

    ```json
    {
      "type": "object",
      "properties": {
        "topics": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "topic": {
                "type": "string"
              },
              "sub_topics": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "topic",
              "sub_topics"
            ]
          }
        }
      },
      "required": [
        "topics"
      ]
    }
    ```

  user_message: >
    {content}
