generate_examples_task:
  system_instruction: >
    Add practical numerical examples to theoretical sections while preserving all existing content only when helpful. 

    Guidelines for adding examples:
    1. Identify sections that would benefit from practical examples
    2. Add examples after theoretical explanations using this format:

    > 💡 **Nota:**
    [Example content with actual numbers, calculations, tables, and visualizations when helpful]

    Example types to add based on LLM/NLU topics:
    - Attention mechanism calculations with concrete scores
    - Transformer layer computations with actual dimensions
    - Tokenization examples with byte-pair encoding
    - Positional encoding visualizations
    - Loss function calculations (cross-entropy, perplexity)
    - Gradient updates in backpropagation through time
    - Embedding space similarity comparisons
    - Layer normalization effects on activations
    - Multi-head attention interactions
    - Training dynamics with learning rate schedules

    Required components:
    1. Use Python code with numpy/pytorch/transformers when appropriate:
    ```python
    import torch
    from transformers import AutoTokenizer, AutoModel
    # Example code demonstrating specific mechanisms
    ```

    2. Include visualizations using Mermaid for architectures:
    ```mermaid
    # Transformer architecture diagrams
    ```

    3. Show mathematical calculations step by step:
    $\text{Step 1: } \text{Attention}(Q,K,V) = \text{softmax}(\frac{QK^T}{\sqrt{d_k}})V$
    $\text{Step 2: } ...$

    4. Use tables for comparing model components:
    | Component | Input Dim | Output Dim | Parameters |
    |-----------|-----------|------------|------------|
    | Self-Attention | 768      | 768        | 590K       |

    5. Include practical training considerations

    Requirements:
    1. Preserve all existing content
    2. Format all mathematical expressions using LaTeX
    3. Use realistic parameter values
    4. Show intermediate calculation steps
    5. Explain the intuition behind the numbers
    6. Connect examples to theoretical concepts
    7. Include analysis where appropriate
    8. Compare different methods when relevant
    9. Use clear variable naming conventions
    10. Add error analysis and statistical tests
    11. Add <!-- END --> comment at the very end of the text after all content

  user_message: >
    Please add practical and helpful examples to this text only where appropriate:

    {content}

    Remember to:
    1. Preserve all existing content
    2. Add examples only where they enhance understanding
    3. Use the specified format with 💡
    4. Keep all mathematical notation and references intact
    5. Add <!-- END --> comment at the very end of the text after all content
