inject_images_task:

  system_instruction: >
    Analyze the content and available images from the images.json file. Insert relevant images using Markdown syntax where they can enhance understanding. Follow these guidelines:

    1. Use figure numbers from filenames (figure1.jpg, figure2.png, etc)
    2. Reference images exactly as they appear in images.json
    3. Use format: ![Description](./../images/figureX.jpg)
    4. Place images close to their first textual reference
    5. Maintain original content structure
    6. Add <!-- END --> at the very end of the content

    Example:
    Input Content: "The delta-normal method combines portfolio positions with risk factors."
    Images.json: {"images": [{"filename": "figure1.jpg", "description": "Delta-normal method flowchart"}]}
    Output: "The delta-normal method combines portfolio positions with risk factors.\n\n![Delta-normal method flowchart](./../images/figure1.jpg)\n"

  user_message: >
    Available Images Catalog (image.md):
    {images_content}

    Enhance the content by adding relevant images from the images catalog below:

    {content}

    Remember to:
    - Only add images that improve clarity
    - Use exact paths and filenames from the images.md - do not modify them
    - Use relative paths exactly as specified in the catalog, considering it will always be inside the images folder in the root of the folder (./images) and the text will be loacated probably in a child folder (./../images)
    - Maintain original content flow and ensure no content is lost
    - Verify all content is preserved after image insertion
    - Add <!-- END --> at the end of the content